var hierarchy =
[
    [ "b2AABB", "structb2_a_a_b_b.html", null ],
    [ "b2BlockAllocator", "classb2_block_allocator.html", null ],
    [ "b2Body", "classb2_body.html", null ],
    [ "b2BodyDef", "structb2_body_def.html", null ],
    [ "b2BodyUserData", "structb2_body_user_data.html", null ],
    [ "b2BroadPhase", "classb2_broad_phase.html", null ],
    [ "b2ClipVertex", "structb2_clip_vertex.html", null ],
    [ "b2Color", "structb2_color.html", null ],
    [ "b2Contact", "classb2_contact.html", null ],
    [ "b2ContactEdge", "structb2_contact_edge.html", null ],
    [ "b2ContactFeature", "structb2_contact_feature.html", null ],
    [ "b2ContactFilter", "classb2_contact_filter.html", null ],
    [ "b2ContactID", "unionb2_contact_i_d.html", null ],
    [ "b2ContactImpulse", "structb2_contact_impulse.html", null ],
    [ "b2ContactListener", "classb2_contact_listener.html", null ],
    [ "b2ContactManager", "classb2_contact_manager.html", null ],
    [ "b2ContactRegister", "structb2_contact_register.html", null ],
    [ "b2DestructionListener", "classb2_destruction_listener.html", null ],
    [ "b2DistanceInput", "structb2_distance_input.html", null ],
    [ "b2DistanceOutput", "structb2_distance_output.html", null ],
    [ "b2DistanceProxy", "structb2_distance_proxy.html", null ],
    [ "b2Draw", "classb2_draw.html", null ],
    [ "b2DynamicTree", "classb2_dynamic_tree.html", null ],
    [ "b2Filter", "structb2_filter.html", null ],
    [ "b2Fixture", "classb2_fixture.html", null ],
    [ "b2FixtureDef", "structb2_fixture_def.html", null ],
    [ "b2FixtureProxy", "structb2_fixture_proxy.html", null ],
    [ "b2FixtureUserData", "structb2_fixture_user_data.html", null ],
    [ "b2GrowableStack< T, N >", "classb2_growable_stack.html", null ],
    [ "b2Jacobian", "structb2_jacobian.html", null ],
    [ "b2Joint", "classb2_joint.html", [
      [ "b2DistanceJoint", "classb2_distance_joint.html", null ],
      [ "b2FrictionJoint", "classb2_friction_joint.html", null ],
      [ "b2GearJoint", "classb2_gear_joint.html", null ],
      [ "b2MotorJoint", "classb2_motor_joint.html", null ],
      [ "b2MouseJoint", "classb2_mouse_joint.html", null ],
      [ "b2PrismaticJoint", "classb2_prismatic_joint.html", null ],
      [ "b2PulleyJoint", "classb2_pulley_joint.html", null ],
      [ "b2RevoluteJoint", "classb2_revolute_joint.html", null ],
      [ "b2WeldJoint", "classb2_weld_joint.html", null ],
      [ "b2WheelJoint", "classb2_wheel_joint.html", null ]
    ] ],
    [ "b2JointDef", "structb2_joint_def.html", [
      [ "b2DistanceJointDef", "structb2_distance_joint_def.html", null ],
      [ "b2FrictionJointDef", "structb2_friction_joint_def.html", null ],
      [ "b2GearJointDef", "structb2_gear_joint_def.html", null ],
      [ "b2MotorJointDef", "structb2_motor_joint_def.html", null ],
      [ "b2MouseJointDef", "structb2_mouse_joint_def.html", null ],
      [ "b2PrismaticJointDef", "structb2_prismatic_joint_def.html", null ],
      [ "b2PulleyJointDef", "structb2_pulley_joint_def.html", null ],
      [ "b2RevoluteJointDef", "structb2_revolute_joint_def.html", null ],
      [ "b2WeldJointDef", "structb2_weld_joint_def.html", null ],
      [ "b2WheelJointDef", "structb2_wheel_joint_def.html", null ]
    ] ],
    [ "b2JointEdge", "structb2_joint_edge.html", null ],
    [ "b2JointUserData", "structb2_joint_user_data.html", null ],
    [ "b2Manifold", "structb2_manifold.html", null ],
    [ "b2ManifoldPoint", "structb2_manifold_point.html", null ],
    [ "b2MassData", "structb2_mass_data.html", null ],
    [ "b2Mat22", "structb2_mat22.html", null ],
    [ "b2Mat33", "structb2_mat33.html", null ],
    [ "b2Pair", "structb2_pair.html", null ],
    [ "b2Position", "structb2_position.html", null ],
    [ "b2Profile", "structb2_profile.html", null ],
    [ "b2QueryCallback", "classb2_query_callback.html", null ],
    [ "b2RayCastCallback", "classb2_ray_cast_callback.html", null ],
    [ "b2RayCastInput", "structb2_ray_cast_input.html", null ],
    [ "b2RayCastOutput", "structb2_ray_cast_output.html", null ],
    [ "b2Rope", "classb2_rope.html", null ],
    [ "b2RopeDef", "structb2_rope_def.html", null ],
    [ "b2RopeTuning", "structb2_rope_tuning.html", null ],
    [ "b2Rot", "structb2_rot.html", null ],
    [ "b2Shape", "classb2_shape.html", [
      [ "b2ChainShape", "classb2_chain_shape.html", null ],
      [ "b2CircleShape", "classb2_circle_shape.html", null ],
      [ "b2EdgeShape", "classb2_edge_shape.html", null ],
      [ "b2PolygonShape", "classb2_polygon_shape.html", null ]
    ] ],
    [ "b2ShapeCastInput", "structb2_shape_cast_input.html", null ],
    [ "b2ShapeCastOutput", "structb2_shape_cast_output.html", null ],
    [ "b2SimplexCache", "structb2_simplex_cache.html", null ],
    [ "b2SolverData", "structb2_solver_data.html", null ],
    [ "b2StackAllocator", "classb2_stack_allocator.html", null ],
    [ "b2StackEntry", "structb2_stack_entry.html", null ],
    [ "b2Sweep", "structb2_sweep.html", null ],
    [ "b2Timer", "classb2_timer.html", null ],
    [ "b2TimeStep", "structb2_time_step.html", null ],
    [ "b2TOIInput", "structb2_t_o_i_input.html", null ],
    [ "b2TOIOutput", "structb2_t_o_i_output.html", null ],
    [ "b2Transform", "structb2_transform.html", null ],
    [ "b2TreeNode", "structb2_tree_node.html", null ],
    [ "b2Vec2", "structb2_vec2.html", null ],
    [ "b2Vec3", "structb2_vec3.html", null ],
    [ "b2Velocity", "structb2_velocity.html", null ],
    [ "b2Version", "structb2_version.html", null ],
    [ "b2World", "classb2_world.html", null ],
    [ "b2WorldManifold", "structb2_world_manifold.html", null ]
];